package solveequation.function;

import java.awt.Color;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import solveequation.expression.Function;
import solveequation.rounded.RoundedTextField;
import solveequation.syntax.ExpressionSyntax;
import solveequation.view.Solve;

/**
 *
 * @author Admin
 */
public class FindFrame extends javax.swing.JFrame {
    private ExpressionSyntax parser;
    private double yVar = 0.0;
    private double zVar = 0.0;
    /**
     * Creates new form FindFrame
     */
    public FindFrame() {
        initComponents();
        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);
        this.setTitle("Dò nghiệm phương trình");
        ImageIcon icon;
        icon = new ImageIcon(getClass().getClassLoader().getResource("baseline_superscript_black_18dp.png"));
        setIconImage(icon.getImage());
        Border roundedBorder = new LineBorder(Color.white, 15, true); // the third parameter - true, says it's round
        jTextArea1.setBorder(roundedBorder);
//        Solve solve = new Solve();
//        JFrame frame = new JFrame("Find Solution");
//        frame.add(solve);
//        frame.setResizable(false);
//        frame.pack();
//        frame.setLocationRelativeTo(null);
//        frame.setVisible(true);
//
//        new Thread(solve).start();
    }
    
    private void solv(){
            String textBox = jTextField1.getText();
            parser = new ExpressionSyntax();
            Function function = parser.parse(textBox);
            double x0 = 0.1;
            double epsilon = 1e-7;
            if(function == null) return;
            double y = function.evaluateAt(x0, yVar, zVar);
            int count = 0; 
            while(Math.abs(y) > 0.00000000001){
                double ff = (-function.evaluateAt(x0, yVar, zVar)+ function.evaluateAt(x0+epsilon, yVar, zVar))/epsilon;
                count++;
                if(count > 1e7){                   
                    jTextArea1.setText("Không thể giải phương trình!!!\n");
                    return;
                }
                x0 = x0 - function.evaluateAt(x0, yVar, zVar)/ff;
//                System.out.println(x0);
//                System.out.println(x0 + " " + y);
                //System.out.println(x0);
                y = function.evaluateAt(x0, yVar, zVar);
            }
            DecimalFormat df = new DecimalFormat("#.#######");
            df.setRoundingMode(RoundingMode.CEILING);
            jTextArea1.setText("Một nghiệm của phương trình " + textBox + " = 0 là: \n" + df.format(x0) + "\n");
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new RoundedTextField(15);
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        roundedButton1 = new solveequation.rounded.RoundedButton();
        jLabel1 = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(80, 190, 460, 50);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nhập vào phương trình  của bạn");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 70, 600, 100);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("= 0");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(590, 180, 90, 60);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(730, 180, 500, 230);

        roundedButton1.setBackground(new java.awt.Color(255, 255, 255));
        roundedButton1.setBorder(null);
        roundedButton1.setText("Find");
        roundedButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        roundedButton1.setGradientBackgroundColor(new java.awt.Color(153, 255, 153));
        roundedButton1.setRounded(true);
        roundedButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roundedButton1MouseClicked(evt);
            }
        });
        jPanel1.add(roundedButton1);
        roundedButton1.setBounds(90, 340, 220, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solveequation/image/find.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 1320, 820);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void roundedButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundedButton1MouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        String textBox = jTextField1.getText();
       //System.out.println(textBox.length());
       // function = parser.parse(textBox);
       solv();
    }//GEN-LAST:event_roundedButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private solveequation.rounded.RoundedButton roundedButton1;
    // End of variables declaration//GEN-END:variables
}
