package solveequation.function;

import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import solveequation.rounded.RoundedTextArea;
import solveequation.rounded.RoundedTextField;
import solveequation.syntax.Error;

/**
 *
 * @author Admin
 */
public class LinearFrame extends javax.swing.JFrame {

    /**
     * Creates new form LinearFrame
     */
    public LinearFrame() {
        initComponents();
//        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);
        this.setTitle("Giải phương trình bậc nhất");
        ImageIcon icon;
        icon = new ImageIcon(getClass().getClassLoader().getResource("baseline_superscript_black_18dp.png"));
        setIconImage(icon.getImage());
        Border roundedBorder = new LineBorder(Color.white, 15, true); // the third parameter - true, says it's round
        solveArea.setBorder(roundedBorder);

//        jScrollPane1.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        a = new RoundedTextField(150);
        b = new RoundedTextField(15);
        jScrollPane1 = new javax.swing.JScrollPane();
        solveArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        roundedButton1 = new solveequation.rounded.RoundedButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("a = ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 180, 94, 62);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 45)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("b = ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 280, 77, 47);

        a.setBackground(new java.awt.Color(255, 255, 255));
        a.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aMouseClicked(evt);
            }
        });
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        jPanel1.add(a);
        a.setBounds(210, 190, 160, 50);

        b.setBackground(new java.awt.Color(255, 255, 255));
        b.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        jPanel1.add(b);
        b.setBounds(210, 280, 160, 50);

        solveArea.setBackground(new java.awt.Color(255, 255, 255));
        solveArea.setColumns(15);
        solveArea.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        solveArea.setRows(5);
        solveArea.setBorder(null);
        solveArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(solveArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(670, 200, 500, 250);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nhập các hệ số");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-10, 20, 669, 179);

        roundedButton1.setBackground(new java.awt.Color(255, 255, 255));
        roundedButton1.setBorder(null);
        roundedButton1.setText("Solve");
        roundedButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        roundedButton1.setGradientBackgroundColor(new java.awt.Color(153, 255, 255));
        roundedButton1.setRounded(true);
        roundedButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(roundedButton1);
        roundedButton1.setBounds(120, 380, 190, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solveequation/image/linear.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 1300, 815);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1308, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseClicked
        // TODO add your handling code here:
        //a.setText("");
    }//GEN-LAST:event_aMouseClicked

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void roundedButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton1ActionPerformed
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("#.#####");
        String aa = a.getText();
        String bb = b.getText();
        if(aa.equals("") || bb.equals("")){
            solveArea.setText("Hãy nhập tất cả hệ số!!! \n");
            return;
        }
        try{
            double aaa = Double.parseDouble(aa);
            double bbb = Double.parseDouble(bb);
            Linear linear = new Linear(aaa, bbb);
//            solveArea.setText(solveArea.getText() + "=> x = -" + bbb + "/" + aaa);
            linear.solve();

            solveArea.setText(linear.getMessage().getMessage() + "\n");
        }
        catch(NumberFormatException ex){
            Error e = new Error();
            e.makeError("Số bạn nhập không hợp lệ !!!");
        }
    }//GEN-LAST:event_roundedButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LinearFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LinearFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LinearFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LinearFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LinearFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private solveequation.rounded.RoundedButton roundedButton1;
    private javax.swing.JTextArea solveArea;
    // End of variables declaration//GEN-END:variables
}
