package solveequation.function;

import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import solveequation.rounded.RoundedTextField;

/**
 *
 * @author Admin
 */
public class QuadraticFrame extends javax.swing.JFrame {

    /**
     * Creates new form QuadraticFrame
     */
    public QuadraticFrame() {
        initComponents();
        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);
        this.setTitle("Giải phương trình bậc 2");
        ImageIcon icon;
        icon = new ImageIcon(getClass().getClassLoader().getResource("baseline_superscript_black_18dp.png"));
        setIconImage(icon.getImage());
        Border roundedBorder = new LineBorder(Color.white, 15, true); // the third parameter - true, says it's round
        solveArea.setBorder(roundedBorder);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        a = new RoundedTextField(15);
        b = new RoundedTextField(15);
        c = new RoundedTextField(15);
        jScrollPane1 = new javax.swing.JScrollPane();
        solveArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        roundedButton1 = new solveequation.rounded.RoundedButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("a = ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 180, 120, 50);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 45)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("b = ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 250, 90, 58);

        a.setBackground(new java.awt.Color(255, 255, 255));
        a.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aMouseClicked(evt);
            }
        });
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        jPanel1.add(a);
        a.setBounds(240, 190, 150, 40);

        b.setBackground(new java.awt.Color(255, 255, 255));
        b.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        jPanel1.add(b);
        b.setBounds(240, 260, 150, 40);

        c.setBackground(new java.awt.Color(255, 255, 255));
        c.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        jPanel1.add(c);
        c.setBounds(240, 330, 150, 40);

        solveArea.setBackground(new java.awt.Color(255, 255, 255));
        solveArea.setColumns(15);
        solveArea.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        solveArea.setRows(5);
        jScrollPane1.setViewportView(solveArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(700, 180, 520, 270);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 45)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("c =");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 310, 110, 70);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nhập các hệ số");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 80, 450, 77);

        roundedButton1.setBackground(new java.awt.Color(255, 255, 255));
        roundedButton1.setBorder(null);
        roundedButton1.setText("Solve");
        roundedButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        roundedButton1.setGradientBackgroundColor(new java.awt.Color(102, 255, 102));
        roundedButton1.setRounded(true);
        roundedButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(roundedButton1);
        roundedButton1.setBounds(120, 400, 190, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solveequation/image/quadratic.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 6, 1300, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1289, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseClicked
        // TODO add your handling code here:
        //a.setText("");
    }//GEN-LAST:event_aMouseClicked

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void roundedButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton1ActionPerformed
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("#.#####");
        String aa = a.getText();
        String bb = b.getText();
        String cc = c.getText();
        if(aa.equals("") || bb.equals("")||cc.equals("")){
            solveArea.setText("Hãy nhập tất cả hệ số!!! \n");
            return;
        }
        try{
            double aaa = Double.parseDouble(aa);
            double bbb = Double.parseDouble(bb);
            double ccc = Double.parseDouble(cc);
            Quadratic quadratic = new Quadratic(aaa, bbb, ccc);
            quadratic.solve();
            if(aaa==0) {
                solveArea.setText(quadratic.getMessage().getMessage());
                return;
            }
            solveArea.setText(quadratic.getMessage().getMessage());
        }
        catch(NumberFormatException ex){
            solveequation.syntax.Error e = new solveequation.syntax.Error();
            e.makeError("Số bạn nhập không hợp lệ !!!");
        }
    }//GEN-LAST:event_roundedButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuadraticFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuadraticFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuadraticFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuadraticFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuadraticFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private solveequation.rounded.RoundedButton roundedButton1;
    private javax.swing.JTextArea solveArea;
    // End of variables declaration//GEN-END:variables
}
