package solveequation.view;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import solveequation.list.Category;
import solveequation.controller.switchcontroller;
import java.awt.GridLayout;
import javax.swing.ImageIcon;
import java.awt.Graphics;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics2D;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JLabel;
import javax.swing.JPanel;



public class MainFrame extends javax.swing.JFrame {
    

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setTitle("Giải phương trình và vẽ đồ thị");
        ///setResizable(false);
        switchcontroller sc = new switchcontroller();
        sc.setView(jLabel1);
        ImageIcon icon;
        icon = new ImageIcon(getClass().getClassLoader().getResource("baseline_stacked_line_chart_black_18dp.png"));
        setIconImage(icon.getImage());
        List<Category> listItem = new ArrayList<>();
//        listItem.add(new Category("Homepage", null, jLabel1));
        listItem.add(new Category("Graph", jpnGraph, jlbGraph));
        listItem.add(new Category("Equation", jpnEquation, jlbEquation));
        listItem.add(new Category("Exit", jpnExit, jlbExit));
        sc.setEven(listItem);
//        Background bg = new Background();
        
        setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnEquation = new RoundedPanel();
        jlbEquation = new javax.swing.JLabel();
        jpnGraph = new RoundedPanel();
        jlbGraph = new javax.swing.JLabel();
        jpnExit = new RoundedPanel();
        jlbExit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        getContentPane().setLayout(null);

        jpnEquation.setBackground(new java.awt.Color(255, 255, 255));
        jpnEquation.setForeground(new java.awt.Color(102, 102, 102));
        jpnEquation.setMinimumSize(new java.awt.Dimension(300, 140));
        jpnEquation.setPreferredSize(new java.awt.Dimension(300, 140));

        jlbEquation.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jlbEquation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbEquation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solveequation/image/baseline_youtube_searched_for_black_18dp.png"))); // NOI18N
        jlbEquation.setText("Giải phương trình");
        jlbEquation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbEquationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnEquationLayout = new javax.swing.GroupLayout(jpnEquation);
        jpnEquation.setLayout(jpnEquationLayout);
        jpnEquationLayout.setHorizontalGroup(
            jpnEquationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnEquationLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbEquation, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jpnEquationLayout.setVerticalGroup(
            jpnEquationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnEquationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbEquation, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jpnEquation);
        jpnEquation.setBounds(930, 320, 390, 150);

        jpnGraph.setBackground(new java.awt.Color(255, 255, 255));
        jpnGraph.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jpnGraphAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jlbGraph.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jlbGraph.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solveequation/image/baseline_show_chart_black_18dp.png"))); // NOI18N
        jlbGraph.setText("        Vẽ đồ thị");
        jlbGraph.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbGraphMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnGraphLayout = new javax.swing.GroupLayout(jpnGraph);
        jpnGraph.setLayout(jpnGraphLayout);
        jpnGraphLayout.setHorizontalGroup(
            jpnGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnGraphLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jlbGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jpnGraphLayout.setVerticalGroup(
            jpnGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnGraphLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jlbGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jpnGraph);
        jpnGraph.setBounds(930, 150, 390, 140);

        jpnExit.setBackground(new java.awt.Color(255, 255, 255));
        jpnExit.setForeground(new java.awt.Color(102, 102, 102));

        jlbExit.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jlbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solveequation/image/baseline_exit_to_app_black_18dp.png"))); // NOI18N
        jlbExit.setText("           Thoát");

        javax.swing.GroupLayout jpnExitLayout = new javax.swing.GroupLayout(jpnExit);
        jpnExit.setLayout(jpnExitLayout);
        jpnExitLayout.setHorizontalGroup(
            jpnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnExitLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jlbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jpnExitLayout.setVerticalGroup(
            jpnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbExit, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jpnExit);
        jpnExit.setBounds(930, 500, 390, 140);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solveequation/image/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpnGraphAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jpnGraphAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnGraphAncestorAdded

    private void jlbGraphMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbGraphMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbGraphMouseClicked

    private void jlbEquationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbEquationMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jlbEquationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame mf = new MainFrame();
                mf.setVisible(true);
                mf.setDefaultCloseOperation(EXIT_ON_CLOSE);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlbEquation;
    private javax.swing.JLabel jlbExit;
    private javax.swing.JLabel jlbGraph;
    private javax.swing.JPanel jpnEquation;
    private javax.swing.JPanel jpnExit;
    private javax.swing.JPanel jpnGraph;
    // End of variables declaration//GEN-END:variables

    public void setLocationRelative(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
